
server:
  port: 8801

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
    # mysql 8.0以后要用这个
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ghaya.mybatis.pojo

#showSql  执行sql自动打印功能
logging:
  file:
    name: log/mybatisSQL.log
  level:
    root: info
    com:
      ghaya:
        mybatis: debug
#    com:
#      example:
#        mapper : debug