fdfs:
    so-timeout: 1500
    connect-timeout: 600
    pool:
        jmx-enabled: false
    thumb.image:
        width: 300
        height: 300
    tracker-list:  192.168.50.249:22122
#    tracker-list:  192.168.160.60:22122